version: '3'
services:
  labelstudio:
    build:
      context: products/labelstudio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=admin@admin.fr
      - LABEL_STUDIO_PASSWORD=xxxxxxxxxxxx
    volumes:
      - /label-studio/data
  mv_camera:
    build:
      context: products/mv_camera
    environment:
      - CLOUD_STORAGE=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    environment:
      - DOMAIN=
    ports:
      - 5000:5000
      - 8080:8080
      - 9090:9090
    volumes:
      - ./products/reverseproxy:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
  s3proxy:
    image: pottava/s3-proxy
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_S3_BUCKET=
      - AWS_S3_KEY_PREFIX=
      - DIRECTORY_LISTINGS=true
