version: '3'
services:
  labelstudio:
    build:
      context: products/labelstudio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=admin@admin.fr
      - LABEL_STUDIO_PASSWORD=xxxxxxxxxxxx
    ports:
      - "8080:8080"
    volumes:
      - /label-studio/data
  mv_camera:
    build:
      context: products/mv_camera
    ports:
      - "5000:5000"
